### ISSUE TITLE
Montage via brew is old

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parallel_patterns#3]
The version of Montage in brew is quite old - v4, which is no longer supported. This can lead to problems, as mViewer, for example, needs freetype on a mac but this dependency is not in the recipe.  The Montage team recommends version 6, and to install it: go to the [Montage web site](http://montage.ipac.caltech.edu) or the [GitHub repo](https://github.com/Caltech-IPAC/Montage) and download. Just type “make” to build.

**Comment by danielskatz** [comment]
also see http://montage.ipac.caltech.edu/docs/montagePy-UG.html

**Comment by sohitmiglani** [comment]
Thanks @danielskatz ! I've removed the installation via brew and added detailed commands for one to be able to download the latest version and using make to build it.
